I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 21, in script
    define gui.show_name = Flase
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = Flase
NameError: name 'Flase' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 21, in script
    define gui.show_name = Flase
  File "C:\Users\xyruj\Desktop\renpy\renpy-8.3.2-sdk\renpy\ast.py", line 2235, in execute
    self.set()
  File "C:\Users\xyruj\Desktop\renpy\renpy-8.3.2-sdk\renpy\ast.py", line 2249, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\xyruj\Desktop\renpy\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/options.rpy", line 21, in <module>
    define gui.show_name = Flase
NameError: name 'Flase' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
EBOYS 1.0
Sat Dec 14 06:57:18 2024
